# Generated by Django 2.2.12 on 2020-09-22 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='手机')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('avatar', models.ImageField(null=True, upload_to='avatar', verbose_name='头像')),
                ('collection', models.CharField(max_length=200, verbose_name='收藏')),
                ('upload', models.CharField(max_length=200, verbose_name='上传')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company')),
            ],
        ),
    ]
